// frontend-react/src/components/create/Create.js
import React, { Component } from "react";
import { Link } from 'react-router-dom';
import axios from 'axios';
import Global from '../../Global';
import { Redirect } from 'react-router-dom';
import SimpleReactValidator from 'simple-react-validator';
import swal from 'sweetalert';
import { v1 as uuidv1 } from 'uuid';

class Create extends Component {

    URL = Global.url;

    nameRef = React.createRef();
    priceRef = React.createRef();
    descriptionRef = React.createRef();

    state = {
        product: {},
        status: null,
        selectedFile: null
    }

    componentWillMount(){
        this.validator = new SimpleReactValidator({
            messages: {
                required: 'Este campo es obligatorio.',
                
            }
        });
    }

    changeState = () => {
        
        this.setState({
            
            product: {
                uuid: uuidv1(),
                name: this.nameRef.current.value,
                description: this.descriptionRef.current.value,
                price: this.priceRef.current.valueAsNumber
            }
        });

        this.validator.showMessages();
        this.forceUpdate();
        
    }

    saveProduct = (e) => {
        e.preventDefault();
        this.changeState()

        if(this.validator.allValid()){

        
            if(this.state.selectedFile !== null){
                
                const formData = new FormData();
                formData.append(
                    'file0',
                    this.state.selectedFile,
                    this.state.selectedFile.name
                );
                
                axios.post(this.URL + "/products/upload", formData)
                    .then(res => {
                        if(res.data){
            
                            this.setState({
                                product: {
                                    uuid: this.state.product.uuid,
                                    name: this.state.product.name,
                                    description: this.state.product.description,
                                    price: this.state.product.price,
                                    image: res.data.image
                                },
                                status: "waiting"
                                
                            });
                            
                            axios.post(this.URL + "/products", this.state.product)
                                .then( res => {
                                    console.log(res);
                                    if(res.data){
                                        this.setState({
                                            product: this.state.product,
                                            status: 'success'
                                        });
                                        

                                        // Alert
                                        swal(
                                            '¡Producto añadido!',
                                            'El producto se ha añadido correctamente.',
                                            'success'
                                        );
                                    
                                    }

                                }).catch( err => {

                                    this.setState({
                                        status: 'error'
                                    });

                                    swal(
                                        'Producto ya registrado',
                                        '¡No se puede insertar dos productos iguales!',
                                        'error'
                                    ); 
                                });
                            
                        }else{
                            this.setState({
                                product: res.data,
                                status: "failed"
                                
                            });

                        }
                    });

        
            }else{

                swal(
                    'Foto no adjuntada',
                    'Sube una imagen del producto.',
                    'error'
                ); 
            }
            

        }else{
            this.setState({
                status: 'error'
            });

            
            this.validator.showMessages();
            this.forceUpdate();
        }        

    }


    fileChange = (event) => {
        this.setState({
            selectedFile: event.target.files[0]
        });
        //console.log(event.target.files[0]);
    }

    render() {

        if(this.state.status === 'success'){
            return(
                <Redirect to={'/home'}></Redirect>
            )
        }

        return (
        <div className="container">
            <div className="row">
            <div className="col-md-12">
                <div className="well well-sm">
                <form className="form-horizontal" onSubmit={this.saveProduct}>
                    <legend className="text-center header">
                    Añade un nuevo producto
                    </legend>
                    <div className="form-group">
                    <span className="col-md-1 col-md-offset-2 text-center" />
                    <div className="col-md-8">
                        <span>
                        <i className="fa fa-laptop" aria-hidden="true" />
                        </span>
                        <input
                        id="name"
                        name="name"
                        type="text"
                        style={{textAlign: 'center'}}
                        placeholder="Nombre"
                        className="form-control"
                        ref={this.nameRef}
                        pattern="^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$"
                        onChange={this.changeState}
                        />
                        {this.validator.message('name', this.state.product.name, 'required')}
                    </div>
                    </div>
                    <div className="form-group">
                    <span className="col-md-1 col-md-offset-2 text-center" />
                    <div className="col-md-8">
                        <span>
                        <i className="fa fa-eur" aria-hidden="true" />
                        </span>
                        <input
                        id="price"
                        name="price"
                        type="number"
                        style={{textAlign: 'center'}}
                        placeholder="Precio"
                        className="form-control"
                        min="1" 
                        step="0.01"
                        pattern='([0-9]*[.])?[0-9]+$'
                        ref={this.priceRef}
                        onChange={this.changeState}
                        required
                        />
                        {this.validator.message('price', this.state.product.price, 'required')}
                    </div>
                    </div>
                    <div className="form-group">
                    <span className="col-md-1 col-md-offset-2 text-center" />
                    <div className="col-md-8">
                        <span>
                        <i className="fa fa-info" aria-hidden="true" />
                        </span>
                        <textarea
                        className="form-control"
                        id="description"
                        name="description"
                        placeholder=" Escriba una breve descripción para el producto mostrando sus principales características."
                        rows={6}
                        defaultValue={""}
                        ref={this.descriptionRef}
                        onChange={this.changeState}
                        />
                        {this.validator.message('description', this.state.product.description, 'required')}
                    </div>
                    </div>
                    <div className="form-group">
                        <label htmlFor="file0"></label>
                        <input type="file" name="file0" onChange={this.fileChange}></input>
                    </div>
                    <div className="form-group">
                    <div className="col-md-12 text-center">
                        <button
                        type="submit"
                        value="Guardar"
                        className="btn btn-outline-primary btn-lg"
                        >
                        Añadir
                        </button>
                        <Link to={'/home'} className="btn btn-outline-secondary btn-lg">
                        Atrás
                        </Link>
                    </div>
                    </div>
                </form>
                </div>
            </div>
            </div>
        </div>
        );
    }
}

export default Create;

// frontend-angular/src/app/components/create/create.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from '../../models/product';
import { ProductService } from '../../services/product.service';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Global } from '../../services/global';
import * as _swal from 'sweetalert';
import { SweetAlert } from 'sweetalert/typings/core';
import { v1 as uuidv1 } from 'uuid';

const swal: SweetAlert = _swal as any;

@Component({
  selector: 'app-create',
  templateUrl: './create.component.html',
  styleUrls: ['./create.component.css'],
  providers: [ProductService]
})
export class CreateComponent implements OnInit {

  public product: Product;
  public n: number;
  

  afuConfig = {
    multiple: false,
    formatsAllowed: ".jpg,.png,.gif,.jpeg",
    maxSize: "50",
    uploadAPI:  {
      url:Global.url+"/products/upload"
    },
    theme: "attachPin",
    hideProgressBar: true,
    hideResetBtn: true,
    hideSelectBtn: false,
    replaceTexts: {
      selectFileBtn: 'Select Files',
      resetBtn: 'Reset',
      uploadBtn: 'Upload',
      dragNDropBox: 'Drag N Drop',
      attachPinBtn: 'Adjuntar foto...',
      afterUploadMsg_success: 'Successfully Uploaded !',
      afterUploadMsg_error: 'Upload Failed !',
    }
  };
  
  
  constructor(
    private _productService: ProductService,
    private _route: ActivatedRoute,
    private _router: Router
  ) { 
    this.product = new Product('','','',this.n,null);
    
   }
 
  ngOnInit(): void {
  }

  onSubmit(){

    this.product.uuid = uuidv1();
    this._productService.create(this.product).subscribe(
      response => {
        // console.log(response);
        if(response == 'Created'){
          
          // Alert
          swal(
            '¡Producto añadido!',
            'El producto se ha añadido correctamente.',
            'success'
          );

          this._router.navigate(['/home']);
        
        } 
      },
      error => {
        if(error.error == 'Conflict'){
          swal(
            'Producto ya registrado',
            '¡No se puede insertar dos productos iguales!',
            'error'
          );
        }else if(error.error == 'Bad Request'){
          swal(
            '¡Foto no adjuntada!',
            'Sube una imagen del producto.',
            'error'
          );
        }
        console.log(error);
      }
    );
  }

  imageUpload(data){
    
    //alert(data.body.image);
    this.product.image = data.body.image;
  }

} 

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" #productForm="ngForm" (ngSubmit)="onSubmit()">
                    <fieldset>
                        <legend class="text-center header">Añade un nuevo producto</legend>
                        
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span>
                            <div class="col-md-8">
                                <span>
                                    <i class="fa fa-laptop" aria-hidden="true"></i>
                                </span>
                                <input #name="ngModel" [(ngModel)]="product.name" id="name" name="name" type="text" placeholder="Nombre" class="form-control" pattern="^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$" required>
                                
                            </div>
                            <small *ngIf="!name.valid && name.touched">El nombre no es válido</small>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span>
                            <div class="col-md-8">
                                <span>
                                    <i class="fa fa-eur" aria-hidden="true"></i>
                                </span>
                                
                                <input #price="ngModel" [(ngModel)]="product.price" id="price" name="price" type="number" min="1" step="1" placeholder="Precio" class="form-control" pattern='([0-9]*[.])?[0-9]+$' required >
                            </div>
                            <small *ngIf="!price.valid && price.touched">El precio no es válido</small>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span>
                            <div class="col-md-8">
                                <span>
                                    <i class="fa fa-info" aria-hidden="true"></i>
                                </span>
                                <textarea #description="ngModel" [(ngModel)]="product.description" class="form-control" id="description" name="description" placeholder="  Escriba una breve descripción para el producto mostrando sus principales características." rows="6" required></textarea>
                            </div>
                            <small *ngIf="!description.valid && description.touched">La descripción no es válida</small>
                        </div>

                        <div class="form-group">
                            <angular-file-uploader
                                [config]="afuConfig"
                                (ApiResponse)="imageUpload($event)">
                            </angular-file-uploader>
                                
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" value="Guardar" class="btn btn-outline-primary btn-lg" [disabled]="productForm.invalid">Añadir</button>
                                <button [routerLink]="['/home']" class="btn btn-outline-secondary btn-lg">Atrás</button>
                                
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
