// frontend-react/src/components/monitores/Monitores.js
import React, { Component } from "react";
import Global from '../../Global';
import { Link, Redirect } from 'react-router-dom';
import swal from 'sweetalert';
import axios from 'axios';
import Sidebar from '../sidebar/Sidebar';

class Monitores extends Component {

    URL = Global.url;

        state = { 
            products: [],
            status: null
        }

        componentWillMount() {
            
            this.getProducts();
            
        }

        getProducts = () => {
            axios.get(this.URL + "/products")
                .then(res => {
                    if(res.data){
                        this.setState({
                            products: res.data,
                            status: 'success'
                        });
                    }else{
                        this.setState({
                            products: res.data,
                            status: 'failed'
                        });
                    }
                    
                });
        }

        deleteProduct = (name) => {
            swal({
                title: "¿Estás seguro?",
                text: "¡Una vez borrado, no podrás recuperar el producto!",
                icon: "warning",
                buttons: [true, true],
                dangerMode: true
              })
              .then((willDelete) => {
    
                if(willDelete){
                    axios.delete(this.URL + "/products/" + name)
                    
                        .then( res => {
    
                            this.setState({
                                products: res.data,
                                status: 'deleted'
                            });
    
                        swal("¡El producto ha sido borrado!", {
                            icon: "success",
                        });
    
                        });
                }else{
                    swal("¡Nada se ha borrado!");
                }
                
              });
                  
        }


    render() {

        if(this.state.status === 'deleted'){
            this.getProducts();
            return(
                <Redirect to={'/monitores'}></Redirect>
            )
        }

        return (
            
            <div className="center">
                    
                    <section id="content">
                    <h1 className="subheader">Monitores</h1>
                    
                        {            
                            this.state.products.filter(product => product.name.includes('Monitor') || product.name.includes('monitor') || product.name.includes('monitores') || product.name.includes('Monitores')).map((filteredName, i) => {
                                //console.log(filteredName)
                                return(
                                    <div id="products" key={filteredName._id}>
                                        <article className="article-item">
                                        
                                            <img src={this.URL+ '/products/display/' + filteredName.image} alt={filteredName.name}></img>
                            
                                            <h3>{filteredName.name}</h3>
                                            <span><strong>Precio: </strong>{filteredName.price}€</span>
                                            <p><strong>Descripción: </strong>{filteredName.description}</p>
                                            <Link to={'/home/editar/' + filteredName.name} className="btn btn-outline-primary" style={{fontSize: '20px', color: 'rgba(124, 6, 160, 0.979)'}}> <i className="fa fa-pencil-square-o" />Editar</Link>
                                                    <button onClick={
                                                        () => {
                                                            this.deleteProduct(filteredName.name)
                                                        }
                                                    } className="btn btn-outline-dark" style={{fontSize: '20px', color: 'red'}}><i className="fa fa-close" />Borrar</button>
                                        </article>
                                    </div>
                                )
                            })
                            
                        }
                        
                    </section>
                    <Sidebar></Sidebar>
                    <div className="clearfix" />
                    <Link to={'/home'} className="btn btn-outline-secondary">Atrás</Link>
                </div>

        )
    }
}

export default Monitores;

// frontend-angular/src/app/components/monitores/monitores.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from '../../models/product';
import { ProductService } from '../../services/product.service';
import { Global } from '../../services/global';
import { Router, ActivatedRoute, Params } from '@angular/router';
import * as _swal from 'sweetalert';
import { SweetAlert } from 'sweetalert/typings/core';

const swal: SweetAlert = _swal as any;

@Component({
  selector: 'app-monitores',
  templateUrl: './monitores.component.html',
  styleUrls: ['./monitores.component.css'],
  providers: [ProductService]
})
export class MonitoresComponent implements OnInit {

  public url: string;
  public products: Array<Product>;
  public title: string;

  constructor(
    private _productService: ProductService,
    private _route: ActivatedRoute,
    private _router: Router
  ) { 
    
    this.url = Global.url;
    this.title = "Monitores";
    
   }

  ngOnInit(): void {

    this._productService.getProductsDevice().subscribe(
      response => {
        //console.log(JSON.stringify(response,null,2));
        if(response){
          this.products = response;
        }
      },
      error => {
        console.log(error);
      }
      
    );
  }

  delete(name){

    swal({
      title: "¿Estás seguro?",
      text: "¡Una vez borrado, no podrás recuperar el producto!",
      icon: "warning",
      buttons: [true, true],
      dangerMode: true
    })
    .then((willDelete) => {
      if (willDelete) {
        this._productService.delete(name).subscribe(
          response => {
            swal("¡El producto ha sido borrado!", {
              icon: "success",
            });

            this._router.navigate(['/home']);
          },
          error => {
            console.log(error);
          }
        );
        
      } else {
        swal("¡Nada se ha borrado!");
      }
    });

    
  }

}

<div class="center">
    
    <section id="content">
        <h4 class="subheader">{{title}}</h4>

        <div id="products" *ngFor="let product of products">
            <article class="article-item" *ngIf="product.name.includes('Monitor') || product.name.includes('monitor') || product.name.includes('Monitores') || product.name.includes('monitores')">
                <div class="image-wrap" >
                    <img src="{{url + '/products/display/' + product.image}}" alt="{{product.name}}">
                </div>

                <h3>{{product.name}}</h3>
                <span><strong>Precio: </strong>{{product.price}}€</span>
                <p><strong>Descripción: </strong>{{product.description}}</p>
                <button [routerLink]="['/home/editar', product.name]" class="btn btn-outline-primary" style="font-size:20px; color:rgba(124, 6, 160, 0.979)"> <i class="fa fa-pencil-square-o"></i>Editar</button>
                <button (click)="delete(product.name)" class="btn btn-outline-dark" style="font-size:20px;color:red"> <i class="fa fa-close"></i>Borrar</button>
                <div class="clearfix"></div>
            </article>
        </div>
        
    </section>
    <a [routerLink]="['/home']" class="btn btn-outline-secondary">Atrás</a>
</div>
