// frontend-angular/src/app/components/edit/edit.component.ts
import { Component, OnInit } from '@angular/core';
import { Product } from '../../models/product';
import { ProductService } from '../../services/product.service';
import { Global } from '../../services/global';
import { Router, ActivatedRoute, Params } from '@angular/router';
import * as _swal from 'sweetalert';
import { SweetAlert } from 'sweetalert/typings/core';

const swal: SweetAlert = _swal as any;

@Component({
  selector: 'app-edit',
  templateUrl: './edit.component.html',
  styleUrls: ['../create/create.component.css'], 
  providers: [ProductService]
})
export class EditComponent implements OnInit {

  public product: Product;
  public n: number;
  public url: string;

  afuConfig = {
    multiple: false,
    formatsAllowed: ".jpg,.png,.gif,.jpeg",
    maxSize: "50",
    uploadAPI:  {
      url:Global.url+"/products/upload"
    },
    theme: "attachPin",
    hideProgressBar: true,
    hideResetBtn: true,
    hideSelectBtn: false,
    replaceTexts: {
      selectFileBtn: 'Select Files',
      resetBtn: 'Reset',
      uploadBtn: 'Upload',
      dragNDropBox: 'Drag N Drop',
      attachPinBtn: 'Adjuntar foto...',
      afterUploadMsg_success: 'Successfully Uploaded !',
      afterUploadMsg_error: 'Upload Failed !',
    }
  };
  

  constructor(
    private _productService: ProductService,
    private _route: ActivatedRoute,
    private _router: Router
  ) { 
    this.product = new Product('','','',this.n,'');
    this.url = Global.url;
   }

  ngOnInit(): void {
    this.getProduct();
  }

  onSubmit(){
    
    this._productService.update(this.product.uuid, this.product).subscribe(
      response => {
      
        if(response == 'OK'){
          
          // Alert
          swal(
            '¡Producto guardado!',
            'El producto se ha editado y guardado correctamente.',
            'success'
          );

          this._router.navigate(['/home']);
        
        }else{
          response.status(405);
        } 

      },
      error => {
        console.log(error);
        swal(
          '¡Producto no guardado!',
          'El producto no se ha editado correctamente.',
          'error'
        );
      }
    );
  }

  getProduct(){
    this._route.params.subscribe(params => {
      
      let uuid = params['uuid'];
     
      this._productService.getProduct(uuid).subscribe(
        response => {
          this.product = response;
          // console.log(this.product);
        },
        error => {
          console.log(error);
        }
      )


    });
  }

  imageUpload(data){
    
    // alert(data.body.image);
    this.product.image = data.body.image;
  }

}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" #productForm="ngForm" (ngSubmit)="onSubmit()">
                    <fieldset>
                        <legend class="text-center header">Editar producto</legend>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span>
                            <div class="col-md-8">
                                <span>
                                    <i class="fa fa-laptop" aria-hidden="true"></i>
                                </span>
                                <input #name="ngModel" [(ngModel)]="product.name" id="name" name="name" type="text"  class="form-control" pattern="^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$" required>
                                
                            </div>
                            
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span>
                            <div class="col-md-8">
                                <span>
                                    <i class="fa fa-eur" aria-hidden="true"></i>
                                </span>
                                
                                <input #price="ngModel" [(ngModel)]="product.price" id="price" name="price" type="number" min="1" step="1" placeholder="Precio" class="form-control" pattern='([0-9]*[.])?[0-9]+$' required >
                            </div>
                            <small *ngIf="!price.valid && price.touched">El precio no es válido</small>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"></span>
                            <div class="col-md-8">
                                <span>
                                    <i class="fa fa-info" aria-hidden="true"></i>
                                </span>
                                <textarea #description="ngModel" [(ngModel)]="product.description" class="form-control" id="description" name="description" placeholder=" Escriba una breve descripción para el producto mostrando sus principales características." rows="6" required></textarea>
                            </div>
                            <small *ngIf="!description.valid && description.touched">La descripción no es válida</small>
                        </div>

                        <div class="form-group">

                            <div class="image-thumb">
                                <img src="{{url + '/products/display/' + product.image}}" alt="{{product.name}}">
                            </div>

                            <angular-file-uploader
                                [config]="afuConfig"
                                (ApiResponse)="imageUpload($event)">
                            </angular-file-uploader>
                                
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" value="Guardar" class="btn btn-outline-primary btn-lg" [disabled]="productForm.invalid">Guardar</button>
                                <button [routerLink]="['/home']" class="btn btn-outline-secondary btn-lg">Atrás</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

// frontend-react/src/components/edit/Edit.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import Global from '../../Global';
import { Redirect } from 'react-router-dom';
import SimpleReactValidator from 'simple-react-validator';
import swal from 'sweetalert';

class Edit extends Component {

    URL = Global.url;
    productName = null;

    nameRef = React.createRef();
    priceRef = React.createRef();
    descriptionRef = React.createRef();

    state = {
        product: {},
        status: null
    }

    componentWillMount(){
        
        this.productUidd = this.props.match.params.name;
        
        this.getProduct(this.productUidd)

        this.validator = new SimpleReactValidator({
            messages: {
                required: 'Este campo es obligatorio.'
                
            }
        });
    }

    getProduct = (uuid) => {
    
        axios.get(this.URL + "/products/" + uuid)
            .then( res => {
                
                this.setState({
                    product: res.data,
                    status: 'success'
                });
            }).catch( err => {
                console.log("Error: " + err);
            });
    }

    changeState = () => {
    
        this.setState({
            
            product: {
                uuid: this.props.match.params.name,
                name: this.nameRef.current.value,
                description: this.descriptionRef.current.value,
                price: this.priceRef.current.valueAsNumber,
                image: this.state.product.image
            }
        });

        this.validator.showMessages();
        this.forceUpdate();
        
    }

    editProduct = (e) => {
        e.preventDefault();
        this.changeState();

        if(this.validator.allValid()){
            
            if(this.state.selectedFile !== undefined){
                const formData = new FormData();
                formData.append(
                    'file0',
                    this.state.selectedFile,
                    this.state.selectedFile.name
                );
                
                axios.post(this.URL + "/products/upload", formData)
                    .then(res => {
                        if(res.data){
            
                            this.setState({
                                product: {
                                    uuid: this.state.product.uuid,
                                    name: this.state.product.name,
                                    description: this.state.product.description,
                                    price: this.state.product.price,
                                    image: res.data.image
                                },
                                status: "waiting"
                                
                            });
         
                            axios.put(this.URL + "/products/" + this.productUidd, this.state.product)
                            .then( res => {
                            
                                if(res.data){
                                
                                    this.setState({
                                        product: res.data,
                                        status: 'exito'
                                    });

                                    // Alert
                                    swal(
                                        '¡Producto guardado!',
                                        'El producto se ha editado y guardado correctamente.',
                                        'success'
                                    );
                                
                                }
                
                                }).catch(err => {

                                    this.setState({
                                        status: 'error'
                                    });

                                    swal(
                                        '¡Producto no guardado!',
                                        'El producto no se ha editado correctamente.',
                                        'error'
                                        ); 
                                    });
                                
                            }else{
                                this.setState({
                                    product: res.data,
                                    status: "failed"
                                    
                                });
                            }
                        });
    
            
                }else{
                    axios.put(this.URL + "/products/" + this.productUidd, this.state.product)
                        .then( res => {
                        
                            if(res.data){
                            
                                this.setState({
                                    product: res.data,
                                    status: 'exito'
                                });

                                // Alert
                                swal(
                                    '¡Producto guardado!',
                                    'El producto se ha editado y guardado correctamente.',
                                    'success'
                                );
                            
                            }
            
                            }).catch(err => {

                                this.setState({
                                    status: 'error'
                                });

                                swal(
                                    '¡Producto no guardado!',
                                    'El producto no se ha editado correctamente.',
                                    'error'
                                    ); 
                                });
                }
                
    
            }else{
                
                this.setState({
                    status: 'error'
                });
    
                this.validator.showMessages();
                this.forceUpdate();
            }        
    
        }

        fileChange = (event) => {
            this.setState({
                selectedFile: event.target.files[0]
            });
            //console.log(event.target.files[0]);
        }

    render() {

        if(this.state.status === 'exito'){
            return(
                <Redirect to={'/home'}></Redirect>
            )
        }

        return (
            
            <div className="container">
                <div className="row">
                    <div className="col-md-12">
                    <div className="well well-sm">
                        <form className="form-horizontal" onSubmit={this.editProduct}>
                        <fieldset>
                            <legend className="text-center header">Editar producto</legend>
                            
                            <div className="form-group">
                            <span className="col-md-1 col-md-offset-2 text-center" />
                            <div className="col-md-8">
                                <span>
                                <i className="fa fa-laptop" aria-hidden="true" />
                                </span>
                                <input  id="name" name="name" type="text" style={{textAlign: 'center'}} defaultValue={this.state.product.name} className="form-control" pattern="^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\s*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$" required ref={this.nameRef} onChange={this.changeState}/>
                            </div>
                            </div>
                            <div className="form-group">
                            <span className="col-md-1 col-md-offset-2 text-center" />
                            <div className="col-md-8">
                                <span>
                                <i className="fa fa-eur" aria-hidden="true" />
                                </span>
                                <input  id="price" name="price" type="number" defaultValue={this.state.product.price} min="1" step="0.01" style={{textAlign: 'center'}} placeholder="Precio" className="form-control" pattern="([0-9]*[.])?[0-9]+$" required ref={this.priceRef} onChange={this.changeState}/>
                                {this.validator.message('price', this.state.product.price, 'required')}
                            </div>
                            
                            </div>
                            <div className="form-group">
                            <span className="col-md-1 col-md-offset-2 text-center" />
                            <div className="col-md-8">
                                <span>
                                <i className="fa fa-info" aria-hidden="true" />
                                </span>
                                <textarea className="form-control" id="description" name="description" placeholder=" Escriba una breve descripción para el producto mostrando sus principales características." defaultValue={this.state.product.description}  rows={6} required ref={this.descriptionRef} onChange={this.changeState}/>
                                {this.validator.message('description', this.state.product.description, 'required')}
                            </div>

                            <div className="form-group">
                                <label htmlFor="file0"></label>
                                <div className="image-thumb">
                                    <img src={this.URL + '/products/display/' + this.state.product.image} alt={this.state.product.name} className="thumb"/>
                                </div>
                                <input type="file" name="file0" onChange={this.fileChange}></input>
                            </div>
                            
                            </div>
                            <div className="form-group">
                            <div className="col-md-12 text-center">
                                <button type="submit" value="Guardar" className="btn btn-outline-primary btn-lg">Guardar</button>
                                <Link to={'/home'} className="btn btn-outline-secondary btn-lg">Atrás</Link>
                            </div>
                            </div>
                        </fieldset>
                        </form>
                    </div>
                    </div>
                </div>
                </div>
        );
    }
}

export default Edit;
